name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "RodrigoTomeES"
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/RodrigoTomeES/react-complete-guide.git
        npm run deploy
        echo "Deployed successfully"
